var hyeditordata = {};
hyeditordata.menu = [
	{
		title:'项目',
		dropItems:[{name:'新建项目'},{name:'保存到服务器'},{name:'保存到本地'}]
	},
	{
		title:'插入',
		dropItems:[{name:'动画组件'},{name:'任务剧情'}]
	},
	{
		title:'模式',
		dropItems:[{name:'编辑'},{name:'行走'},{name:'射击'}]
	},
	{
		title:'帮助',
		dropItems:[{name:'帮助说明'},{name:'关于'}]
	}
];
hyeditordata.projectTree = {
	name:'所有项目',
	leaf:false,
	contextMenu:[{name:'新项目'},{name:'呵呵'}],
	childNodes:[
		{
			name:'项目1',
			leaf:false,
			childNodes:[
				{
					name:'地图',
					leaf:false,
					childNodes:[]
				}
			]
		},
		{
			name:'项目2',
			leaf:false,
			childNodes:[
				{
					name:'地图',
					leaf:false,
					childNodes:[]
				}
			]
		},
		{
			name:'项目3',
			leaf:false,
			childNodes:[
				{
					name:'地图',
					leaf:false,
					childNodes:[]
				}
			]
		}
	]
};

hyeditordata.map = {};
hyeditordata.map.resTree = {
	name:"地图素材",
	leaf:false,
	childNodes:[
		{
			name:'地表背景',
			leaf:false,
			childNodes:[
				{
					name:'土地',
					leaf:true,
					dragClipBoardData:{
						drawType:1,
						bush:'image/ground/sand.png'
					}
				},
				{
					name:'草地',
					leaf:true,
					dragClipBoardData:{
						drawType:1,
						bush:'image/ground/grass.png'
					}
				}
			]
		},
		{
			name:'地表画笔',
			leaf:false,
			childNodes:[
				{
					name:'土地',
					leaf:true,
					dragClipBoardData:{
						drawType:2,
						bush:'image/ground/sand.png'
					}
				},
				{
					name:'草地',
					leaf:true,
					dragClipBoardData:{
						drawType:2,
						bush:'image/ground/grass.png'
					}
				}
			]
		},
		{
			name:'地表砖块',
			leaf:false,
			childNodes:[
				{
					name:'砖块1',
					leaf:true,
					dragClipBoardData:{
						drawType:3,
						texture:{
							src:'image/block/block_4.png',
							srcX:0,
							srcY:0,
							srcWidth:0,
							srcHeight:0
						}
					}
				}
			]
		},
		{
			name:'地表装饰',
			leaf:false,
			childNodes:[]
		},
		{
			name:'地面单位',
			leaf:false,
			childNodes:[
				{
					name:'房子1',
					leaf:true,
					dragClipBoardData:{
						drawType:4,
						objectJson:{
							width:160,
							height:110,
							texture:{
								src:'image/object/house1.png',
								srcX:0,
								srcY:0,
								srcWidth:0,
								srcHeight:0
							}
						}
					}
				},
				{
					name:'房子2',
					leaf:true,
					dragClipBoardData:{
						drawType:4,
						objectJson:{
							width:128,
							height:128,
                            localCollidedPolygon:[{x:-64,y:64},{x:64,y:64},{x:64,y:-64},{x:64,y:64}],
							texture:{
								src:'image/object/house2.png',
								srcX:0,
								srcY:0,
								srcWidth:0,
								srcHeight:0
							}
						}
					}
				}
			]
		},
		{
			name:'地面精灵',
			leaf:false,
			childNodes:[
				{
					name:'精灵1',
					leaf:true,
					dragClipBoardData:{
						drawType:5,
						objectJson:{
							name:'精灵',
							x:0,
							y:0,
							width:70,
							height:124,
							anchorX:0.5,
							anchorY:0.5,
							rotateAngleZ:0.0,
							alpha:1,
							texture:null,
							actionNames:[
								{name:'walk_e'},
								{name:'walk_ne'},
								{name:'walk_n'},
								{name:'walk_nw'},
								{name:'walk_w'},
								{name:'walk_sw'},
								{name:'walk_s'},
								{name:'walk_se'}
							],
							actionFrames:null,
							childNodes:[
								{
									name:'封皮1',
									x:0,
									y:0,
									width:70,
									height:124,
									anchorX:0.5,
									anchorY:0.5,
									rotateAngleZ:0.0,
									alpha:1,
									texture:{
										src:HY.Core.Config.Paths.Image+"role/role1.png",
										srcX:0,
										srcY:0,
										srcWidth:70,
										srcHeight:124
									},
									actionFrames:{
										"walk_e":[
											{
												time:0.1,
												tween:false,
												spriteParam:{
													x:0,
													y:0,
													width:70,
													height:124,
													anchorX:0.5,
													anchorY:0.5,
													rotateAngleZ:0.0,
													alpha:1,
													texture:{
														src:HY.Core.Config.Paths.Image+"role/role1.png",
														srcX:0,
														srcY:248,
														srcWidth:70,
														srcHeight:124
													}
												}
											},
											{
												time:0.2,
												tween:false,
												spriteParam:{
													x:0,
													y:0,
													width:70,
													height:124,
													anchorX:0.5,
													anchorY:0.5,
													rotateAngleZ:0.0,
													alpha:1,
													texture:{
														src:HY.Core.Config.Paths.Image+"role/role1.png",
														srcX:70,
														srcY:248,
														srcWidth:70,
														srcHeight:124
													}
												}
											},
											{
												time:0.3,
												tween:false,
												spriteParam:{
													x:0,
													y:0,
													width:70,
													height:124,
													anchorX:0.5,
													anchorY:0.5,
													rotateAngleZ:0.0,
													alpha:1,
													texture:{
														src:HY.Core.Config.Paths.Image+"role/role1.png",
														srcX:140,
														srcY:248,
														srcWidth:70,
														srcHeight:124
													}
												}
											},
											{
												time:0.4,
												tween:false,
												spriteParam:{
													x:0,
													y:0,
													width:70,
													height:124,
													anchorX:0.5,
													anchorY:0.5,
													rotateAngleZ:0.0,
													alpha:1,
													texture:{
														src:HY.Core.Config.Paths.Image+"role/role1.png",
														srcX:210,
														srcY:248,
														srcWidth:70,
														srcHeight:124
													}
												}
											},
										],
										"walk_ne":[
											{
												time:0.1,
												tween:false,
												spriteParam:{
													x:0,
													y:0,
													width:70,
													height:124,
													anchorX:0.5,
													anchorY:0.5,
													rotateAngleZ:0.0,
													alpha:1,
													texture:{
														src:HY.Core.Config.Paths.Image+"role/role1.png",
														srcX:0,
														srcY:868,
														srcWidth:70,
														srcHeight:124
													}
												}
											},
											{
												time:0.2,
												tween:false,
												spriteParam:{
													x:0,
													y:0,
													width:70,
													height:124,
													anchorX:0.5,
													anchorY:0.5,
													rotateAngleZ:0.0,
													alpha:1,
													texture:{
														src:HY.Core.Config.Paths.Image+"role/role1.png",
														srcX:70,
														srcY:868,
														srcWidth:70,
														srcHeight:124
													}
												}
											},
											{
												time:0.3,
												tween:false,
												spriteParam:{
													x:0,
													y:0,
													width:70,
													height:124,
													anchorX:0.5,
													anchorY:0.5,
													rotateAngleZ:0.0,
													alpha:1,
													texture:{
														src:HY.Core.Config.Paths.Image+"role/role1.png",
														srcX:140,
														srcY:868,
														srcWidth:70,
														srcHeight:124
													}
												}
											},
											{
												time:0.4,
												tween:false,
												spriteParam:{
													x:0,
													y:0,
													width:70,
													height:124,
													anchorX:0.5,
													anchorY:0.5,
													rotateAngleZ:0.0,
													alpha:1,
													texture:{
														src:HY.Core.Config.Paths.Image+"role/role1.png",
														srcX:210,
														srcY:868,
														srcWidth:70,
														srcHeight:124
													}
												}
											}
										],
										"walk_n":[
											{
												time:0.1,
												tween:false,
												spriteParam:{
													x:0,
													y:0,
													width:70,
													height:124,
													anchorX:0.5,
													anchorY:0.5,
													rotateAngleZ:0.0,
													alpha:1,
													texture:{
														src:HY.Core.Config.Paths.Image+"role/role1.png",
														srcX:0,
														srcY:372,
														srcWidth:70,
														srcHeight:124
													}
												}
											},
											{
												time:0.2,
												tween:false,
												spriteParam:{
													x:0,
													y:0,
													width:70,
													height:124,
													anchorX:0.5,
													anchorY:0.5,
													rotateAngleZ:0.0,
													alpha:1,
													texture:{
														src:HY.Core.Config.Paths.Image+"role/role1.png",
														srcX:70,
														srcY:372,
														srcWidth:70,
														srcHeight:124
													}
												}
											},
											{
												time:0.3,
												tween:false,
												spriteParam:{
													x:0,
													y:0,
													width:70,
													height:124,
													anchorX:0.5,
													anchorY:0.5,
													rotateAngleZ:0.0,
													alpha:1,
													texture:{
														src:HY.Core.Config.Paths.Image+"role/role1.png",
														srcX:140,
														srcY:372,
														srcWidth:70,
														srcHeight:124
													}
												}
											},
											{
												time:0.4,
												tween:false,
												spriteParam:{
													x:0,
													y:0,
													width:70,
													height:124,
													anchorX:0.5,
													anchorY:0.5,
													rotateAngleZ:0.0,
													alpha:1,
													texture:{
														src:HY.Core.Config.Paths.Image+"role/role1.png",
														srcX:210,
														srcY:372,
														srcWidth:70,
														srcHeight:124
													}
												}
											}
										],
										"walk_nw":[
											{
												time:0.1,
												tween:false,
												spriteParam:{
													x:0,
													y:0,
													width:70,
													height:124,
													anchorX:0.5,
													anchorY:0.5,
													rotateAngleZ:0.0,
													alpha:1,
													texture:{
														src:HY.Core.Config.Paths.Image+"role/role1.png",
														srcX:0,
														srcY:744,
														srcWidth:70,
														srcHeight:124
													}
												}
											},
											{
												time:0.2,
												tween:false,
												spriteParam:{
													x:0,
													y:0,
													width:70,
													height:124,
													anchorX:0.5,
													anchorY:0.5,
													rotateAngleZ:0.0,
													alpha:1,
													texture:{
														src:HY.Core.Config.Paths.Image+"role/role1.png",
														srcX:70,
														srcY:744,
														srcWidth:70,
														srcHeight:124
													}
												}
											},
											{
												time:0.3,
												tween:false,
												spriteParam:{
													x:0,
													y:0,
													width:70,
													height:124,
													anchorX:0.5,
													anchorY:0.5,
													rotateAngleZ:0.0,
													alpha:1,
													texture:{
														src:HY.Core.Config.Paths.Image+"role/role1.png",
														srcX:140,
														srcY:744,
														srcWidth:70,
														srcHeight:124
													}
												}
											},
											{
												time:0.4,
												tween:false,
												spriteParam:{
													x:0,
													y:0,
													width:70,
													height:124,
													anchorX:0.5,
													anchorY:0.5,
													rotateAngleZ:0.0,
													alpha:1,
													texture:{
														src:HY.Core.Config.Paths.Image+"role/role1.png",
														srcX:210,
														srcY:744,
														srcWidth:70,
														srcHeight:124
													}
												}
											}
										],
										"walk_w":[
											{
												time:0.1,
												tween:false,
												spriteParam:{
													x:0,
													y:0,
													width:70,
													height:124,
													anchorX:0.5,
													anchorY:0.5,
													rotateAngleZ:0.0,
													alpha:1,
													texture:{
														src:HY.Core.Config.Paths.Image+"role/role1.png",
														srcX:0,
														srcY:124,
														srcWidth:70,
														srcHeight:124
													}
												}
											},
											{
												time:0.2,
												tween:false,
												spriteParam:{
													x:0,
													y:0,
													width:70,
													height:124,
													anchorX:0.5,
													anchorY:0.5,
													rotateAngleZ:0.0,
													alpha:1,
													texture:{
														src:HY.Core.Config.Paths.Image+"role/role1.png",
														srcX:70,
														srcY:124,
														srcWidth:70,
														srcHeight:124
													}
												}
											},
											{
												time:0.3,
												tween:false,
												spriteParam:{
													x:0,
													y:0,
													width:70,
													height:124,
													anchorX:0.5,
													anchorY:0.5,
													rotateAngleZ:0.0,
													alpha:1,
													texture:{
														src:HY.Core.Config.Paths.Image+"role/role1.png",
														srcX:140,
														srcY:124,
														srcWidth:70,
														srcHeight:124
													}
												}
											},
											{
												time:0.4,
												tween:false,
												spriteParam:{
													x:0,
													y:0,
													width:70,
													height:124,
													anchorX:0.5,
													anchorY:0.5,
													rotateAngleZ:0.0,
													alpha:1,
													texture:{
														src:HY.Core.Config.Paths.Image+"role/role1.png",
														srcX:210,
														srcY:124,
														srcWidth:70,
														srcHeight:124
													}
												}
											}
										],
										"walk_sw":[
											{
												time:0.1,
												tween:false,
												spriteParam:{
													x:0,
													y:0,
													width:70,
													height:124,
													anchorX:0.5,
													anchorY:0.5,
													rotateAngleZ:0.0,
													alpha:1,
													texture:{
														src:HY.Core.Config.Paths.Image+"role/role1.png",
														srcX:0,
														srcY:496,
														srcWidth:70,
														srcHeight:124
													}
												}
											},
											{
												time:0.2,
												tween:false,
												spriteParam:{
													x:0,
													y:0,
													width:70,
													height:124,
													anchorX:0.5,
													anchorY:0.5,
													rotateAngleZ:0.0,
													alpha:1,
													texture:{
														src:HY.Core.Config.Paths.Image+"role/role1.png",
														srcX:70,
														srcY:496,
														srcWidth:70,
														srcHeight:124
													}
												}
											},
											{
												time:0.3,
												tween:false,
												spriteParam:{
													x:0,
													y:0,
													width:70,
													height:124,
													anchorX:0.5,
													anchorY:0.5,
													rotateAngleZ:0.0,
													alpha:1,
													texture:{
														src:HY.Core.Config.Paths.Image+"role/role1.png",
														srcX:140,
														srcY:496,
														srcWidth:70,
														srcHeight:124
													}
												}
											},
											{
												time:0.4,
												tween:false,
												spriteParam:{
													x:0,
													y:0,
													width:70,
													height:124,
													anchorX:0.5,
													anchorY:0.5,
													rotateAngleZ:0.0,
													alpha:1,
													texture:{
														src:HY.Core.Config.Paths.Image+"role/role1.png",
														srcX:210,
														srcY:496,
														srcWidth:70,
														srcHeight:124
													}
												}
											}
										],
										"walk_s":[
											{
												time:0.1,
												tween:false,
												spriteParam:{
													x:0,
													y:0,
													width:70,
													height:124,
													anchorX:0.5,
													anchorY:0.5,
													rotateAngleZ:0.0,
													alpha:1,
													texture:{
														src:HY.Core.Config.Paths.Image+"role/role1.png",
														srcX:0,
														srcY:0,
														srcWidth:70,
														srcHeight:124
													}
												}
											},
											{
												time:0.2,
												tween:false,
												spriteParam:{
													x:0,
													y:0,
													width:70,
													height:124,
													anchorX:0.5,
													anchorY:0.5,
													rotateAngleZ:0.0,
													alpha:1,
													texture:{
														src:HY.Core.Config.Paths.Image+"role/role1.png",
														srcX:70,
														srcY:0,
														srcWidth:70,
														srcHeight:124
													}
												}
											},
											{
												time:0.3,
												tween:false,
												spriteParam:{
													x:0,
													y:0,
													width:70,
													height:124,
													anchorX:0.5,
													anchorY:0.5,
													rotateAngleZ:0.0,
													alpha:1,
													texture:{
														src:HY.Core.Config.Paths.Image+"role/role1.png",
														srcX:140,
														srcY:0,
														srcWidth:70,
														srcHeight:124
													}
												}
											},
											{
												time:0.4,
												tween:false,
												spriteParam:{
													x:0,
													y:0,
													width:70,
													height:124,
													anchorX:0.5,
													anchorY:0.5,
													rotateAngleZ:0.0,
													alpha:1,
													texture:{
														src:HY.Core.Config.Paths.Image+"role/role1.png",
														srcX:210,
														srcY:0,
														srcWidth:70,
														srcHeight:124
													}
												}
											}
										],
										"walk_se":[
											{
												time:0.1,
												tween:false,
												spriteParam:{
													x:0,
													y:0,
													width:70,
													height:124,
													anchorX:0.5,
													anchorY:0.5,
													rotateAngleZ:0.0,
													alpha:1,
													texture:{
														src:HY.Core.Config.Paths.Image+"role/role1.png",
														srcX:0,
														srcY:620,
														srcWidth:70,
														srcHeight:124
													}
												}
											},
											{
												time:0.2,
												tween:false,
												spriteParam:{
													x:0,
													y:0,
													width:70,
													height:124,
													anchorX:0.5,
													anchorY:0.5,
													rotateAngleZ:0.0,
													alpha:1,
													texture:{
														src:HY.Core.Config.Paths.Image+"role/role1.png",
														srcX:70,
														srcY:620,
														srcWidth:70,
														srcHeight:124
													}
												}
											},
											{
												time:0.3,
												tween:false,
												spriteParam:{
													x:0,
													y:0,
													width:70,
													height:124,
													anchorX:0.5,
													anchorY:0.5,
													rotateAngleZ:0.0,
													alpha:1,
													texture:{
														src:HY.Core.Config.Paths.Image+"role/role1.png",
														srcX:140,
														srcY:620,
														srcWidth:70,
														srcHeight:124
													}
												}
											},
											{
												time:0.4,
												tween:false,
												spriteParam:{
													x:0,
													y:0,
													width:70,
													height:124,
													anchorX:0.5,
													anchorY:0.5,
													rotateAngleZ:0.0,
													alpha:1,
													texture:{
														src:HY.Core.Config.Paths.Image+"role/role1.png",
														srcX:210,
														srcY:620,
														srcWidth:70,
														srcHeight:124
													}
												}
											}
										]
									}
								}
							]
						}
					}
				}
			]
		},
		{
			name:"天空单位",
			leaf:false,
			childNodes:[]
		}
	]
};

hyeditordata.assemble = {};
hyeditordata.assemble.resTree = {
	name:'图片素材',
	leaf:false,
	expanded:true,
	childNodes:[
		{
			name:'图片1',
			leaf:true,
			extraData:{
				src:HY.Core.Config.Paths.Image+"role/role1.png",
				srcX:0,
				srcY:0,
				srcWidth:70,
				srcHeight:124
			}
		},
		{
			name:'图片2',
			leaf:true,
			extraData:{
				src:HY.Core.Config.Paths.Image+"role/role1.png",
				srcX:70,
				srcY:0,
				srcWidth:70,
				srcHeight:124
			}
		},
		{
			name:'图片3',
			leaf:true,
			extraData:{
				src:HY.Core.Config.Paths.Image+"role/role1.png",
				srcX:140,
				srcY:0,
				srcWidth:70,
				srcHeight:124
			}
		},
		{
			name:'图片4',
			leaf:true,
			extraData:{
				src:HY.Core.Config.Paths.Image+"role/role1.png",
				srcX:210,
				srcY:0,
				srcWidth:70,
				srcHeight:124
			}
		}
	]
};

hyeditordata.assemble.structNode = {};
hyeditordata.assemble.structNode.rootContextMenu = [
	{name:'新零件'},
	{name:'帮助'}
];
hyeditordata.assemble.structNode.nodeContextMenu = [
	{name:'新零件'},
	{name:'删除'},
	{name:'帮助'}
];
hyeditordata.assemble.structNode.nodeNormalIcon = {
	src:HY.Core.Config.Paths.Image+HY.Core.Config.HySysFiles.Icon,
	srcX:80,
	srcY:0,
	srcWidth:20,
	srcHeight:20
};
hyeditordata.assemble.structNode.nodeExpandIcon = {
	src:HY.Core.Config.Paths.Image+HY.Core.Config.HySysFiles.Icon,
	srcX:80,
	srcY:0,
	srcWidth:20,
	srcHeight:20
};

hyeditordata.assemble.newUnit = {};
hyeditordata.assemble.newUnit.contextMenu = [
	{name:'移动'},
	{name:'旋转'},
	{name:'尺寸'},
	{name:'锚点'},
	{name:'上移一层'},
	{name:'移到顶层'},
	{name:'下移一层'},
	{name:'移至底层'},
	{name:'删除'}
];

hyeditordata.assemble.actionList = {};
hyeditordata.assemble.actionList.contextMenu = [
	{name:'新动作'},
	{name:'帮助'}
];
hyeditordata.assemble.actionList.itemContextMenu = [
	{name:'新动作'},
	{name:'播放'},
	{name:'暂停'},
	{name:'删除'},
	{name:'帮助'}
];

hyeditordata.assemble.timeline = {};
hyeditordata.assemble.timeline.contextMenu = [
	{name:'插入关键帧'},
	{name:'删除关键帧'},
	{name:'插入补间动画'},
	{name:'取消补间动画'}
]