HY.Game = {};

HY.Game.RESIZENORTHWEST = 1;
HY.Game.RESIZENORTHEAST = 2;
HY.Game.RESIZESOUTHEAST = 3;
HY.Game.RESIZESOUTHWEST = 4;


HY.Game.NODE = {};
HY.Game.NODE.EDITMODE = {};
HY.Game.NODE.EDITMODE.NONE = 0;
HY.Game.NODE.EDITMODE.ANGLE = 1;
HY.Game.NODE.EDITMODE.ANCHOR = 2;
HY.Game.NODE.EDITMODE.POSITION = 3;
HY.Game.NODE.EDITMODE.RESIZE = 4;